### ISSUE TITLE
AWS Ops Review - Incident Management and Root Cause Review

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2901] opened 2024-03-08 00:35 UTC
**Describe the Issue**
Review platform Incident Management needs for Enterprise-Ready operations, and create a solution/process that allows for easy tracking\reviews, along with a possible 'Feedback' loop to help improve communications with client teams and feed our iterative improvement process 

**Additional Context**
To be part of Operations documentation\processes and when possible turned into an automated process eventually through the use of new ticketing/service management software

**Acceptance Criteria**
- Review Public Cloud platform Ops incident management needs
- Review and incorporate any best practices 
- Review possibility to have a Incident Management request process actually built into the client Project Registry/Tracker UI
- Create Incident Management initial draft documentation for discussion and follow up with further tickets

**Comment by jon-mc-git** [comment] 2024-05-03 02:09
Review of initial needs for Enterprise-Ready operations was done and draft documentation and workflow were completed for upcoming discussions.  Closing

**Comment by mitovskaol** [comment] 2024-05-31 21:40
@jon-mc-git @ThibaultBC @MarisaBC  This ticket seems to be a duplicate of #2660 Review of operational platform Change Management needs and create a solution for client request tracking and general feedback tracking, as it has the same DoD. Please review and if confirmed, DELETE ticket as it skews the team burn out rate as the points assigned to this ticket are counted towards the points completed within the Sprint when in fact no work was actually done.

**Comment by jon-mc-git** [comment] 2024-06-14 20:28
Change & Incident management as two different ops processes were under two separate tickets.  All related docs located in team Ops docs - 007..\Operations\Ops Process Areas

**Comment by jon-mc-git** [comment] 2024-10-23 21:55
Old ticket - was closed and re-opened again.  Any questions on the ticket were addressed at the time.  Ticket should be closed

**Closed as completed** 2024-10-23 22:19 UTC
Labels: Operations
